name: action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.list.outputs.projects }}
    steps:
      - id: compare
        uses: hogelog/commit-diff-action@HEAD
      - run: |
          echo '${{ steps.compare.outputs.diffsJSON }}'
          echo '${{ steps.compare.outputs.diffs }}'
