name: matrix

on:
  push:
    branches:
      - main

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.list.outputs.projects }}
    steps:
      - id: compare
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { data: comparison } = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.before,
              head: context.payload.after,
            })
            const diffs = comparison.files
              .filter(file => file.patch)
              .map(file => (file.filename))
            const result = JSON.stringify(diffs, null, 0)
            console.log(result)
            return result
      - id: list
        run: |
          echo '${{ steps.compare.outputs.result }}' | jq -r '.[]' | egrep -o 'projects/[^/]+' | sort -u | jq -nRc '[inputs]' | tee projects.json
          echo "projects=$(cat projects.json)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: list
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.list.outputs.projects) }}
    steps:
      - run: echo ${{ matrix.project }}
