# This is a basic workflow to help you get started with Actions

name: random command

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit $(($RANDOM % 2 == 0))
